volumes:
  swole:
    external: true
  pg-admin:
    external: true
services:
  postgres:
    build:
      context: ./relational-data
      dockerfile: ./Dockerfile.dev
    volumes:
      - swole:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: swole
      POSTGRES_USER: swole
      POSTGRES_DB: swole
    ports:
      - 15432:5432
  api:
    build:
      context: ./api
      dockerfile: ./Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
    environment:
      DATABASE_URL: postgresql://swole:swole@postgres/swole
      WAIT_HOSTS: postgres:5432

      SIGNING_KEY:
      WAIT_BEFORE:
      WAIT_TIMEOUT:
  ghi:
    image: node:lts-bullseye
    command: /bin/bash run.sh
    working_dir: /app
    volumes:
      - ./ghi:/app
    ports:
      - "3000:3000"
    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: "0.0.0.0"
      PUBLIC_URL: http://localhost:3000
      REACT_APP_API_API_HOST: http://localhost:8000
      REACT_APP_API_NINJAS: https://api-ninjas.com/exercises #remember that urls dont have to add exercises
  pg-admin:
    image: dpage/pgadmin4
    volumes:
      - pg-admin:/var/lib/pgadmin
    ports:
      - 8082:80
    environment:
      PGADMIN_DEFAULT_EMAIL: allyhaas@gmail.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_DISABLE_POSTFIX: 1
